"""initial_schema

Revision ID: 452e0572a690
Revises: 
Create Date: 2026-05-01 20:15:44.709962

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452e0572a690'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_parameters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kdf_algorithm', sa.String(length=20), server_default=sa.text("'argon2id'"), nullable=False),
    sa.Column('kdf_salt', sa.LargeBinary(), nullable=False),
    sa.Column('kdf_memory_cost', sa.Integer(), server_default=sa.text('65536'), nullable=False),
    sa.Column('kdf_time_cost', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('kdf_parallelism', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=20), server_default=sa.text("'aes-256-gcm'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("id = '00000000-0000-0000-0000-000000000001'", name=op.f('ck_crypto_parameters_crypto_parameters_singleton_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crypto_parameters'))
    )
    op.create_table('event_emission_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_emission_log'))
    )
    op.create_table('holding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('declared_custody_model', sa.String(length=30), nullable=False),
    sa.Column('declared_signing_model', sa.String(length=30), nullable=False),
    sa.Column('declared_geographic_distribution', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('declared_inheritance_configured', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('declared_security_notes', sa.Text(), nullable=True),
    sa.Column('subtype_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('display_color', sa.String(length=7), server_default=sa.text("'#000000'"), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("holding_type IN ('account','purse','strongbox','vault')", name=op.f('ck_holding_holding_type_in_set')),
    sa.CheckConstraint("purpose IN ('spending','reserve','long_term','transit','undeclared')", name=op.f('ck_holding_purpose_in_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding'))
    )
    op.create_index('ix_holding_holding_type_active', 'holding', ['holding_type'], unique=False, postgresql_where=sa.text('is_archived = FALSE'))
    op.create_index('ix_holding_purpose_active', 'holding', ['purpose'], unique=False, postgresql_where=sa.text('is_archived = FALSE'))
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('net_amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('fee_sats', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('counterparty_label', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=40), nullable=True),
    sa.Column('categorized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("direction IN ('incoming','outgoing','internal')", name=op.f('ck_ledger_entry_ledger_entry_direction_in_set')),
    sa.CheckConstraint("source IN ('onchain_transaction','lightning_payment','custodial_event')", name=op.f('ck_ledger_entry_ledger_entry_source_in_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry'))
    )
    op.create_index('ix_ledger_entry_source_reference', 'ledger_entry', ['source', 'source_reference'], unique=False)
    op.create_index('ix_ledger_entry_timestamp', 'ledger_entry', [sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_ledger_entry_uncategorized', 'ledger_entry', ['id'], unique=False, postgresql_where=sa.text('category IS NULL'))
    op.create_table('onchain_transaction',
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('raw_hex', sa.Text(), nullable=True),
    sa.Column('confirmation_height', sa.Integer(), nullable=True),
    sa.Column('block_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('fee_sats', sa.BigInteger(), nullable=True),
    sa.Column('size_vbytes', sa.Integer(), nullable=True),
    sa.Column('is_coinjoin_suspected', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('txid', name=op.f('pk_onchain_transaction'))
    )
    op.create_index('ix_onchain_transaction_block_time', 'onchain_transaction', [sa.text('block_time DESC')], unique=False)
    op.create_index('ix_onchain_transaction_unconfirmed', 'onchain_transaction', ['txid'], unique=False, postgresql_where=sa.text('confirmation_height IS NULL'))
    op.create_table('runtime_configuration',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_runtime_configuration'))
    )
    op.create_table('secret',
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('authentication_tag', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_secret'))
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('preset', sa.String(length=20), nullable=False),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('base_currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('locale', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("id = '00000000-0000-0000-0000-000000000001'", name=op.f('ck_user_profile_user_profile_singleton_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_table('descriptor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('change_expression', sa.Text(), nullable=True),
    sa.Column('network', sa.String(length=10), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('gap_limit', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('is_watch_only', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('last_scanned_height', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("network IN ('mainnet','testnet','signet','regtest')", name=op.f('ck_descriptor_descriptor_network_in_set')),
    sa.CheckConstraint('is_watch_only = TRUE', name=op.f('ck_descriptor_descriptor_is_watch_only')),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_descriptor_holding_id_holding'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_descriptor')),
    sa.UniqueConstraint('expression', name='uq_descriptor_expression')
    )
    op.create_index(op.f('ix_descriptor_holding_id'), 'descriptor', ['holding_id'], unique=False)
    op.create_table('holding_type_change_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('previous_type', sa.String(length=20), nullable=False),
    sa.Column('new_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_holding_type_change_log_holding_id_holding'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding_type_change_log'))
    )
    op.create_table('ledger_entry_holding_link',
    sa.Column('ledger_entry_id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('holding_amount_sats', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_ledger_entry_holding_link_holding_id_holding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entry.id'], name=op.f('fk_ledger_entry_holding_link_ledger_entry_id_ledger_entry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ledger_entry_id', 'holding_id', name=op.f('pk_ledger_entry_holding_link'))
    )
    op.create_index(op.f('ix_ledger_entry_holding_link_holding_id'), 'ledger_entry_holding_link', ['holding_id'], unique=False)
    op.create_table('payment_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount_sats', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('destination_address', sa.String(length=100), nullable=True),
    sa.Column('bip21_uri', sa.Text(), nullable=True),
    sa.Column('psbt_base64', sa.Text(), nullable=True),
    sa.Column('signed_transaction_hex', sa.Text(), nullable=True),
    sa.Column('broadcast_txid', sa.String(length=64), nullable=True),
    sa.Column('lightning_invoice', sa.Text(), nullable=True),
    sa.Column('lightning_payment_hash', sa.String(length=64), nullable=True),
    sa.Column('resulting_ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("payment_type IN ('onchain','lightning')", name=op.f('ck_payment_request_payment_request_type_in_set')),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_payment_request_holding_id_holding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resulting_ledger_entry_id'], ['ledger_entry.id'], name=op.f('fk_payment_request_resulting_ledger_entry_id_ledger_entry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_request'))
    )
    op.create_index('ix_payment_request_broadcast_txid', 'payment_request', ['broadcast_txid'], unique=False, postgresql_where=sa.text('broadcast_txid IS NOT NULL'))
    op.create_index(op.f('ix_payment_request_holding_id'), 'payment_request', ['holding_id'], unique=False)
    op.create_index(op.f('ix_payment_request_status'), 'payment_request', ['status'], unique=False)
    op.create_table('sweep_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_holding_id', sa.Uuid(), nullable=False),
    sa.Column('destination_holding_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('minimum_balance_sats', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('maximum_per_period_sats', sa.BigInteger(), nullable=True),
    sa.Column('requires_user_confirmation', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('safety_warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_executed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("trigger_type IN ('scheduled','threshold','manual')", name=op.f('ck_sweep_policy_sweep_policy_trigger_type_in_set')),
    sa.CheckConstraint('source_holding_id <> destination_holding_id', name=op.f('ck_sweep_policy_sweep_policy_source_neq_destination')),
    sa.ForeignKeyConstraint(['destination_holding_id'], ['holding.id'], name=op.f('fk_sweep_policy_destination_holding_id_holding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_holding_id'], ['holding.id'], name=op.f('fk_sweep_policy_source_holding_id_holding'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sweep_policy'))
    )
    op.create_index('ix_sweep_policy_enabled', 'sweep_policy', ['is_enabled'], unique=False, postgresql_where=sa.text('is_enabled = TRUE'))
    op.create_index(op.f('ix_sweep_policy_source_holding_id'), 'sweep_policy', ['source_holding_id'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('derivation_path', sa.String(length=100), nullable=False),
    sa.Column('is_change', sa.Boolean(), nullable=False),
    sa.Column('derivation_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('first_seen_height', sa.Integer(), nullable=True),
    sa.Column('is_reused', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptor.id'], name=op.f('fk_address_descriptor_id_descriptor'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address')),
    sa.UniqueConstraint('descriptor_id', 'is_change', 'derivation_index', name='uq_address_descriptor_branch_index')
    )
    op.create_index('ix_address_lookup', 'address', ['address'], unique=False)
    op.create_table('broadcast_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_request_id', sa.Uuid(), nullable=False),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('transaction_hex', sa.Text(), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_request_id'], ['payment_request.id'], name=op.f('fk_broadcast_attempt_payment_request_id_payment_request'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_attempt'))
    )
    op.create_index(op.f('ix_broadcast_attempt_payment_request_id'), 'broadcast_attempt', ['payment_request_id'], unique=False)
    op.create_table('custodial_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('provider_kind', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_id', sa.String(length=50), nullable=False),
    sa.Column('api_credential_reference', sa.String(length=200), nullable=False),
    sa.Column('api_secret_reference', sa.String(length=200), nullable=False),
    sa.Column('api_passphrase_reference', sa.String(length=200), nullable=True),
    sa.Column('can_read', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('can_trade', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('can_withdraw', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('whitelist_address', sa.String(length=100), nullable=False),
    sa.Column('whitelist_address_descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('last_polled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_known_balance_sats', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("provider_kind IN ('exchange','broker','p2p_venue')", name=op.f('ck_custodial_provider_custodial_provider_kind_in_set')),
    sa.CheckConstraint('can_read = TRUE', name=op.f('ck_custodial_provider_custodial_provider_can_read_true')),
    sa.CheckConstraint('can_trade = FALSE', name=op.f('ck_custodial_provider_custodial_provider_can_trade_false')),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_custodial_provider_holding_id_holding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['whitelist_address_descriptor_id'], ['descriptor.id'], name=op.f('fk_custodial_provider_whitelist_address_descriptor_id_descriptor'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custodial_provider')),
    sa.UniqueConstraint('holding_id', name='uq_custodial_provider_holding_id')
    )
    op.create_index(op.f('ix_custodial_provider_is_active'), 'custodial_provider', ['is_active'], unique=False)
    op.create_table('sweep_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sweep_policy_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.Column('pre_balance_sats', sa.BigInteger(), nullable=False),
    sa.Column('intended_amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_withdrawal_id', sa.String(length=100), nullable=True),
    sa.Column('expected_txid', sa.String(length=64), nullable=True),
    sa.Column('confirmed_txid', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sweep_policy_id'], ['sweep_policy.id'], name=op.f('fk_sweep_execution_sweep_policy_id_sweep_policy'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sweep_execution'))
    )
    op.create_index('ix_sweep_execution_pending', 'sweep_execution', ['status'], unique=False, postgresql_where=sa.text("status NOT IN ('completed','failed','cancelled')"))
    op.create_index('ix_sweep_execution_policy', 'sweep_execution', ['sweep_policy_id', sa.text('triggered_at DESC')], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('amount_sats', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receiving_address', sa.String(length=100), nullable=True),
    sa.Column('receiving_address_id', sa.Uuid(), nullable=True),
    sa.Column('bip21_uri', sa.Text(), nullable=True),
    sa.Column('bolt11', sa.Text(), nullable=True),
    sa.Column('payment_hash', sa.String(length=64), nullable=True),
    sa.Column('resulting_ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("invoice_type IN ('onchain','lightning')", name=op.f('ck_invoice_invoice_type_in_set')),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], name=op.f('fk_invoice_holding_id_holding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_address_id'], ['address.id'], name=op.f('fk_invoice_receiving_address_id_address'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resulting_ledger_entry_id'], ['ledger_entry.id'], name=op.f('fk_invoice_resulting_ledger_entry_id_ledger_entry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_index(op.f('ix_invoice_holding_id'), 'invoice', ['holding_id'], unique=False)
    op.create_index('ix_invoice_receiving_address', 'invoice', ['receiving_address'], unique=False, postgresql_where=sa.text('receiving_address IS NOT NULL'))
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_table('utxo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descriptor_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('value_sats', sa.BigInteger(), nullable=False),
    sa.Column('confirmation_height', sa.Integer(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_spent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('spent_in_txid', sa.String(length=64), nullable=True),
    sa.Column('hygiene_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_utxo_address_id_address'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptor.id'], name=op.f('fk_utxo_descriptor_id_descriptor'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utxo')),
    sa.UniqueConstraint('txid', 'vout', name='uq_utxo_outpoint')
    )
    op.create_index('ix_utxo_descriptor_unspent', 'utxo', ['descriptor_id'], unique=False, postgresql_where=sa.text('is_spent = FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utxo_descriptor_unspent', table_name='utxo', postgresql_where=sa.text('is_spent = FALSE'))
    op.drop_table('utxo')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index('ix_invoice_receiving_address', table_name='invoice', postgresql_where=sa.text('receiving_address IS NOT NULL'))
    op.drop_index(op.f('ix_invoice_holding_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('ix_sweep_execution_policy', table_name='sweep_execution')
    op.drop_index('ix_sweep_execution_pending', table_name='sweep_execution', postgresql_where=sa.text("status NOT IN ('completed','failed','cancelled')"))
    op.drop_table('sweep_execution')
    op.drop_index(op.f('ix_custodial_provider_is_active'), table_name='custodial_provider')
    op.drop_table('custodial_provider')
    op.drop_index(op.f('ix_broadcast_attempt_payment_request_id'), table_name='broadcast_attempt')
    op.drop_table('broadcast_attempt')
    op.drop_index('ix_address_lookup', table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_sweep_policy_source_holding_id'), table_name='sweep_policy')
    op.drop_index('ix_sweep_policy_enabled', table_name='sweep_policy', postgresql_where=sa.text('is_enabled = TRUE'))
    op.drop_table('sweep_policy')
    op.drop_index(op.f('ix_payment_request_status'), table_name='payment_request')
    op.drop_index(op.f('ix_payment_request_holding_id'), table_name='payment_request')
    op.drop_index('ix_payment_request_broadcast_txid', table_name='payment_request', postgresql_where=sa.text('broadcast_txid IS NOT NULL'))
    op.drop_table('payment_request')
    op.drop_index(op.f('ix_ledger_entry_holding_link_holding_id'), table_name='ledger_entry_holding_link')
    op.drop_table('ledger_entry_holding_link')
    op.drop_table('holding_type_change_log')
    op.drop_index(op.f('ix_descriptor_holding_id'), table_name='descriptor')
    op.drop_table('descriptor')
    op.drop_table('user_profile')
    op.drop_table('secret')
    op.drop_table('runtime_configuration')
    op.drop_index('ix_onchain_transaction_unconfirmed', table_name='onchain_transaction', postgresql_where=sa.text('confirmation_height IS NULL'))
    op.drop_index('ix_onchain_transaction_block_time', table_name='onchain_transaction')
    op.drop_table('onchain_transaction')
    op.drop_index('ix_ledger_entry_uncategorized', table_name='ledger_entry', postgresql_where=sa.text('category IS NULL'))
    op.drop_index('ix_ledger_entry_timestamp', table_name='ledger_entry')
    op.drop_index('ix_ledger_entry_source_reference', table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('job')
    op.drop_index('ix_holding_purpose_active', table_name='holding', postgresql_where=sa.text('is_archived = FALSE'))
    op.drop_index('ix_holding_holding_type_active', table_name='holding', postgresql_where=sa.text('is_archived = FALSE'))
    op.drop_table('holding')
    op.drop_table('event_emission_log')
    op.drop_table('crypto_parameters')
    # ### end Alembic commands ###
